### ISSUE TITLE
ES6 class support

### ISSUE THREAD

**Issue by supersteves** [mihaip/react-closure-compiler#15]
I haven't tried this yet, but presumably it doesn't support ES6 class syntax:

``` javascript
class X extends React.Component {
}
```

https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

**Comment by mihaip** [comment]
Completed with https://github.com/mihaip/react-closure-compiler/commit/b4bb529ed7df1cdc3e3cee2255fb22816fde5ab3.
