### ISSUE TITLE
Does this work with React 16?

### ISSUE THREAD

**Issue by fatso83** [mihaip/react-closure-compiler#23]
I see the project seems to have been inactive for some time Is this still being used at Quip, like mentioned in the README, or has its use been surpassed by better options? Is there any documentation on how to interface this with more traditional javascript build pipelines?

**Comment by mihaip** [comment]
We're still actively using this at Quip (and making changes as needed, the most recent commits are from a couple of months ago).

React 15.4 and later drop Closure Compiler compatibility (if running React itself through the compiler, a result of changes like facebook/react@f7076b7759c57b95da21ffca892ddbdcf3ffed02), thus we're currently still on 15.3 and haven't looked at 16. We will most likely eventually support later React versions by not compiling them together with our code, but we don't have a compelling reason to do so yet.

The README is all the documentation there is, so I'm afraid you're on your own if you want to do anything too different (though I'm happy to answer questions if you get stuck). We already have a custom (Java-based) Closure Compiler runner at Quip, thus adding the custom pass (and the warning guard) was not a significant change for us. How are you invoking the Closure Compiler right now?

**Comment by fatso83** [comment]
Thanks for the feedback. We are about to migrate our setup from Meteor to a more platform agnostic one, so this is part of our research phase :-)
